using CaptureTools.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace CaptureTools
{
    public class FFmpegPreset : Tracked, IConfigNode
    {
        public const string nodeName = "CAPTURETOOLS_FFMPEG_PRESET";
        public static string defaultAuthor = "User";

        public string path;
        public UrlDir.UrlConfig config;

        private string name;
        private string command;
        private string author;

        public string Name { get => name; set => SetTracked(ref name, value); }
        public string Command { get => command; set => SetTracked(ref command, value); }
        public string Author { get => author; set => SetTracked(ref author, value); }

        #region Serialisation

        public FFmpegPreset(string name = "New Preset", string command = "", string author = "")
        {
            this.name = name;
            this.command = command;
            this.author = author;

            Modified = false;
            Editable = true;
        }

        public FFmpegPreset(FFmpegPreset presetToCopy)
        {
            this.name = presetToCopy.name;
            this.command = presetToCopy.command;
            this.author = presetToCopy.author;
            Editable = presetToCopy.Editable;

            Modified = false;
        }

        public void Save(ConfigNode node)
        {
            node.name = nodeName;
            node.SetValue("name", name, true);
            node.SetValue("author", author, true);
            node.SetValue("command", Uri.EscapeDataString(command), true);
        }

        public void Load(ConfigNode node)
        {
            // Required values.
            name = RequireValue(node, "name");
            command = Uri.UnescapeDataString(RequireValue(node, "command"));

            // Additional values.
            node.TryGetValue("author", ref author);
        }

        private string RequireValue(ConfigNode node, string key)
        {
            string value = string.Empty;
            if (node.TryGetValue(key, ref value))
                return value;

            throw new Exception($"Required value '{key}' not found in config node '{node.name}'.");
        }

        public void SaveToFile()
        {
            // Only allowed modified, editable presets that were loaded via PluginData.
            if (!Editable || config != null)
                return;

            // Save to path, otherwise a default path will be used.
            if (string.IsNullOrEmpty(path))
            {
                char[] invalidChars = Path.GetInvalidFileNameChars();
                string fileName = new string(Name.Select(c => invalidChars.Contains(c) ? '_' : c).ToArray()) + ".cfg";
                path = Path.Combine(FFmpegPresetLoader.pluginDataPath, fileName);
            }

            string directory = Path.GetDirectoryName(path);

            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            ConfigNode file = new ConfigNode();
            ConfigNode presetNode = new ConfigNode(nodeName);
            Save(presetNode);
            file.AddNode(presetNode);
            file.Save(path, "Autogenerated by Capture Tools. Please remember not to include more than one preset per file in PluginData.");

            Modified = false;
        }

        public void LoadFromFile()
        {
            if (config != null)
                TryLoadPresetFromURLConfig(this, config);
            else if (!string.IsNullOrEmpty(path))
                TryLoadPresetFromFile(this, path);
            else
            {
                CTDebug.LogError("Attempted to reload a preset without a config or path. Cannot reload.");
                return;
            }

            Modified = false;
        }

        public static bool TryLoadPresetFromFile(FFmpegPreset preset, string file)
        {
            try
            {
                ConfigNode fileNode = ConfigNode.Load(file);
                int count = fileNode.nodes.Count;
                List<ConfigNode> presetNodes = new List<ConfigNode>();

                for (int i = 0; i < count; i++)
                {
                    if (fileNode.nodes[i].name != FFmpegPreset.nodeName)
                        continue;

                    presetNodes.Add(fileNode.nodes[i]);

                    if (presetNodes.Count > 1)
                        throw new Exception($"Multiple FFmpeg presets found in {file}. Capture Tools only allows one per file in PluginData " +
                                $"in order to make saving and loading faster.");
                }

                if (!presetNodes.Any())
                    return false;

                preset.Load(presetNodes.First());
                preset.path = file;
                preset.config = null;
                preset.Editable = true;

                return true;
            }
            catch (Exception e)
            {
                CTDebug.LogError($"Error while loading FFmpeg preset from plugin data in {file}: {e.Message}");
                return false;
            }
        }

        public static bool TryLoadPresetFromURLConfig(FFmpegPreset preset, UrlDir.UrlConfig urlConfig)
        {
            try
            {
                preset.Load(urlConfig.config);
                preset.config = urlConfig;
                preset.path = Path.Combine(KSPUtil.ApplicationRootPath, "GameData", urlConfig.parent.url + ".cfg");
                preset.Editable = false;

                return true;
            }
            catch (Exception e)
            {
                CTDebug.LogError($"Error while loading FFmpeg preset from config in {urlConfig.url}: {e.Message}");
                return false;
            }
        }

        public void DeleteFile()
        {
            if (config != null || !Editable)
            {
                CTDebug.LogError("Attempted to delete a preset that is not editable or loaded from a URL config. Cannot delete.");
                return;
            }

            if (string.IsNullOrEmpty(path))
            {
                CTDebug.LogError("Attempted to delete a preset without a path. Cannot delete.");
                return;
            }

            // Delete the file at path and remove the preset from the loader.
            if (File.Exists(path))
            {
                File.Delete(path);
                FFmpegPresetLoader.RemovePreset(this);
                CTDebug.Log($"Deleted FFmpeg preset file at {path}.");
            }
            else
            {
                CTDebug.LogError($"Attempted to delete a preset file that does not exist at {path}.");
            }
        }

        #endregion
    }
}
